//
//  Token.swift
//  Tokenizer3
//
//  Created by James Bean on 11/8/15.
//  Copyright © 2015 James Bean. All rights reserved.
//


import Foundation

/**
Token that is generated by Tokenizer (either a TokenContainer, or a token of specific type)
*/
public protocol Token: CustomStringConvertible {
    
    var identifier: String { get set }
    var startIndex: Int { get set }
    var stopIndex: Int { get set }
}


public struct TokenLineComment: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    
    public init(startIndex: Int, stopIndex: Int) {
        self.identifier = "LineComment"
        self.startIndex = startIndex
        self.stopIndex = stopIndex
    }
    
    private func getDescription() -> String {
        return "\(identifier) from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenBlockCommentStart: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    
    public init(startIndex: Int) {
        self.identifier = "BlockCommentStart"
        self.startIndex = startIndex
        self.stopIndex = startIndex + 1
    }
    
    private func getDescription() -> String {
        return "\(identifier) from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenBlockCommentStop: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    
    public init(startIndex: Int) {
        self.identifier = "BlockCommentStop"
        self.startIndex = startIndex
        self.stopIndex = startIndex + 1
    }
    
    private func getDescription() -> String {
        return "\(identifier) from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenIndent: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    
    public init(startIndex: Int, stopIndex: Int) {
        self.identifier = "Indentation"
        self.startIndex = startIndex
        self.stopIndex = stopIndex
    }
    
    private func getDescription() -> String {
        return "\(identifier) from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenString: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    public var indentationLevel: Int?
    
    public var value: String
    
    // use length fo string to determine stop index
    
    public init(
        identifier: String,
        value: String,
        startIndex: Int,
        indentationLevel: Int? = nil
    )
    {
        self.identifier = identifier
        self.value = value
        self.startIndex = startIndex
        self.stopIndex = startIndex + value.characters.count - 1 // check
        self.indentationLevel = indentationLevel
    }
    
    private func getDescription() -> String {
        return "\(identifier): \(value); from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenInt: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    public var indentationLevel: Int?
    
    public var value: Int
    
    // stop value should not be necessary
    public init(
        identifier: String,
        value: Int,
        startIndex: Int,
        stopIndex: Int,
        indentationLevel: Int? = nil
    )
    {
        self.identifier = identifier
        self.value = value
        self.startIndex = startIndex
        self.stopIndex = stopIndex
        self.indentationLevel = indentationLevel
    }

    private func getDescription() -> String {
        return "\(identifier): \(value); from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenFloat: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    public var indentationLevel: Int?
    
    public var value: Float
    
    // perhaps stop index can be calculated as well (turn into string locally, count chars here)
    public init(
        identifier: String,
        value: Float,
        startIndex: Int,
        stopIndex: Int,
        indentationLevel: Int? = nil
    )
    {
        self.identifier = identifier
        self.value = value
        self.startIndex = startIndex
        self.stopIndex = stopIndex
        self.indentationLevel = indentationLevel
    }
    
    private func getDescription() -> String {
        return "\(identifier): \(value); from \(startIndex) to \(stopIndex)"
    }
}

public struct TokenDuration: Token {
    
    public var description: String { return getDescription() }
    
    public var identifier: String
    public var startIndex: Int
    public var stopIndex: Int
    public var indentationLevel: Int?
    
    // (beats, subdivisionValue)
    public var value: (Int, Int)
    
    public init(
        identifier: String,
        value: (Int, Int),
        startIndex: Int,
        stopIndex: Int,
        indentationLevel: Int? = nil
    )
    {
        self.identifier = identifier
        self.value = value
        self.startIndex = startIndex
        self.stopIndex = stopIndex
        self.indentationLevel = indentationLevel
    }
    
    private func getDescription() -> String {
        return "\(identifier): \(value); from \(startIndex) to \(stopIndex)"
    }
}